# Generated by Django 5.1.11 on 2025-08-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_jobimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='Jobs.job', verbose_name=''),
        ),
    ]
